05-18 PR list
arumduri/bootstrap pull request #22
Opened 2021-05-18 01:12 UTC by hwang1588

『new description translation』

'utilities'
- background description translation(new)

----------------------------------------------------

『update description translation』

'utilities'
- api description translation(update)

'helpers'
- stretched-link description translation(update)
- visually-hidden description translation(update)

2021-05-18 01:17 UTC, hwang1588 commented on site/content/docs/5.0/utilities/background.md
> +description: `background-color` 을 통해 의미를 전달하고 그라디언트로 꾸밈을 추가 합니다.
을 -> 를 변경, 추가 번역에서 수정 예정

2021-05-24 07:17 UTC, hwang1588 commented
netfliy 사용하려면 별도의 이용료가 필요한거 같네요...우선은 무시해주세요

2021-05-24 07:46 UTC, alexkoala requested changes

2021-05-24 07:46 UTC, alexkoala commented on site/content/docs/5.0/utilities/background.md
> +description: `background-color` 을 통해 의미를 전달하고 그라디언트로 꾸밈을 추가 합니다.
```suggestion
description: "`background-color` 를 통해 의미를 전달하고 그라디언트로 꾸밈을 추가 합니다."
```
YAML error

2021-05-24 07:47 UTC, alexkoala commented
> netfliy 사용하려면 별도의 이용료가 필요한거 같네요...아래의 failed는 무시해주시기 바랍니다.

Netlify 문제가 아니라 YAML 문법에 오류가 있는 것으로 보입니다. Review 확인 후 수정 부탁드립니다.

2021-05-24 07:56 UTC, alexkoala approved these changes

2021-05-24 07:59 UTC, merged