Modify migration
arumduri/bootstrap pull request #23
Opened 2021-05-20 10:13 UTC by jjulee

ing

2021-05-20 23:28 UTC, hwang1588 reviewed
check

2021-05-24 06:02 UTC, jjulee commented
@alexkoala 
modifier class를 어떻게 번역해야 사용자들이 한번에 이해할까.... 고민했는데.. `modifier` 그대로가 나을거 같아 수정합니다. 
후에 다른 의견이 있다면 반영하도록 하겠습니다.

우선 이대로 머지 부탁드립니다.

2021-05-24 07:55 UTC, alexkoala requested changes
`데이터`가 맞습니다.

2021-05-24 07:55 UTC, alexkoala commented on site/content/docs/5.0/components/collapse.md
> +접을 수 있는 영역에 accordion(아코디언) 같은 그룹 관리를 추가하려면, 데이타 속성 `data-bs-parent="#selector"`를 추가합니다. 데모를 참조해 주세요.
```suggestion
접을 수 있는 영역에 accordion(아코디언) 같은 그룹 관리를 추가하려면, 데이터 속성 `data-bs-parent="#selector"`를 추가합니다. 데모를 참조해 주세요.
```

2021-05-24 07:55 UTC, alexkoala commented on site/content/docs/5.0/components/collapse.md
> +옵션은 JavaScript나 데이타 속성으로 줄 수 있습니다. 데이타 속성의 경우는 `data-bs-parent=""` 처럼 `data-bs-` 에 옵션 명을 추가합니다.
```suggestion
옵션은 JavaScript나 데이터 속성으로 줄 수 있습니다. 데이터 속성의 경우는 `data-bs-parent=""` 처럼 `data-bs-` 에 옵션 명을 추가합니다.
```

2021-05-24 07:55 UTC, alexkoala commented on site/content/docs/5.0/components/collapse.md
> +      <td>요소의 콜랩스를 처리합니다. (DOM 요소에 저장되어 있는 데이타를 삭제합니다)</td>
```suggestion
      <td>요소의 콜랩스를 처리합니다. (DOM 요소에 저장되어 있는 데이터를 삭제합니다)</td>
```

2021-05-24 07:55 UTC, alexkoala commented on site/content/docs/5.0/components/dropdowns.md
> +        요소의 드롭다운을 없앱니다.(DOM 요소에 지정되어 있는 데이타를 삭제합니다)
```suggestion
        요소의 드롭다운을 없앱니다.(DOM 요소에 지정되어 있는 데이터를 삭제합니다)
```

2021-05-24 07:55 UTC, alexkoala commented on site/content/docs/5.0/components/modal.md
> +모달의 요소를 없앱니다.(DOM 요소에 저장되어 있는 데이타를 삭제합니다)
```suggestion
모달의 요소를 없앱니다.(DOM 요소에 저장되어 있는 데이터를 삭제합니다)
```

2021-05-24 07:55 UTC, alexkoala commented on site/content/docs/5.0/components/popovers.md
> +요소의 팝오버를 숨기고 없앱니다(DOM 요소에 저장된 데이타를 삭제합니다). 위임을 사용하는 팝오버([the `selector` option](#options) 를 사용하여 작성된 것) 는 자식의 트리거 요소로 인해 개벌적으로 없앨 수 없습니다.
```suggestion
요소의 팝오버를 숨기고 없앱니다(DOM 요소에 저장된 데이터를 삭제합니다). 위임을 사용하는 팝오버([the `selector` option](#options) 를 사용하여 작성된 것) 는 자식의 트리거 요소로 인해 개벌적으로 없앨 수 없습니다.
```

2021-05-24 07:55 UTC, alexkoala commented on site/content/docs/5.0/forms/form-control.md
> +데이타 목록을 사용하면 `<input>` 안에서 엑세스(및 자동 보완) 할 수 있는 `<option>` 그룹을 작성할 수 있습니다. 이들은 `<select>` 요소와 비슷하지만 목록 표시에는 많은 제한과 차이가 있습니다. 대부분의 브라우저나 운영 체계는 `<datalist>` 요소를 어느 정도 지원하고 있지만, 그 표시에는 일관성이 없습니다.
```suggestion
데이터 목록을 사용하면 `<input>` 안에서 엑세스(및 자동 보완) 할 수 있는 `<option>` 그룹을 작성할 수 있습니다. 이들은 `<select>` 요소와 비슷하지만 목록 표시에는 많은 제한과 차이가 있습니다. 대부분의 브라우저나 운영 체계는 `<datalist>` 요소를 어느 정도 지원하고 있지만, 그 표시에는 일관성이 없습니다.
```

2021-05-24 07:55 UTC, alexkoala commented on site/content/docs/5.0/getting-started/download.md
> +Bootstrap의 `package.json`에는 다음 키에 몇몇 메타데이타가 포함되어 있습니다:
```suggestion
Bootstrap의 `package.json`에는 다음 키에 몇몇 메타데이터가 포함되어 있습니다:
```

2021-05-24 07:55 UTC, alexkoala commented on site/content/docs/5.0/getting-started/javascript.md
> +description: 선택적 JavaScript 플러그인으로 Bootstrap에 생명을 불어넣으세요. 각 플러그인, 데이타 및 프로그래밍 방식 API 옵션 등에 대해 알아보세요.
```suggestion
description: 선택적 JavaScript 플러그인으로 Bootstrap에 생명을 불어넣으세요. 각 플러그인, 데이터 및 프로그래밍 방식 API 옵션 등에 대해 알아보세요.
```

2021-05-24 07:55 UTC, alexkoala commented on site/content/docs/5.0/getting-started/javascript.md
> +거의 모든 Bootstrap 플러그인은 데이타 속성 (JavaScript 기능을 사용하는 권장 방법)과 함께 HTML을 통해서만 활성화 및 구성할 수 있습니다. **단일 요소의 한 세트의 데이타 속성만 사용해야 합니다.** (예: 동일한 버튼으로 툴팁과 모달을 트리거할 수 없음)
```suggestion
거의 모든 Bootstrap 플러그인은 데이터 속성 (JavaScript 기능을 사용하는 권장 방법)과 함께 HTML을 통해서만 활성화 및 구성할 수 있습니다. **단일 요소의 한 세트의 데이터 속성만 사용해야 합니다.** (예: 동일한 버튼으로 툴팁과 모달을 트리거할 수 없음)
```

2021-05-24 07:55 UTC, alexkoala commented on site/content/docs/5.0/migration.md
> +- 비대상 Chrome < 60
```suggestion
- Internet Explorer 10 및 11 지원 종료
- Microsoft Edge 16 미만 (Legacy Edge) 지원 종료
- Firefox 60 미만 지원 종료
- Safari 12 미만 지원 종료
- iOS Safari 12 미만 지원 종료
- Chrome 60 미만 지원 종료
```
`비대상`보다는 `지원 종료`가 더 이해하기 쉬울 것 같습니다.

2021-05-24 08:09 UTC, jjulee commented
@alexkoala  수정하였습니다. 확인 부탁드립니다.
https://github.com/arumduri/bootstrap/pull/23/commits/964396f134840fe209e191976690256ec863c650

2021-05-24 08:11 UTC, alexkoala approved these changes

2021-05-24 08:13 UTC, merged