description translation(update)
arumduri/bootstrap pull request #24
Opened 2021-05-24 09:00 UTC by hwang1588

『new description translation』

- null
----------------------------------------------------

『update description translation』

'utilities'

- borders description translation(update)

- colors description translation(update)

- display description translation(update)

- flex description translation(update)

2021-05-24 09:04 UTC, hwang1588 commented
풀요청으로 인한 충돌은 없는데 지속적으로 Netlify에서 checks failed가 발생하네요.. 정확한 사용 방법을 잘 모르겠습니다.. 도움이 필요합니다..

2021-05-24 10:26 UTC, alexkoala commented
다른 문서로 향하는 하이퍼링크에 문제가 있습니다.

2021-05-24 10:27 UTC, alexkoala commented
> 풀요청으로 인한 충돌은 없는데 지속적으로 Netlify에서 checks failed가 발생하네요.. 정확한 사용 방법을 잘 모르겠습니다.. 도움이 필요합니다..

다른 문서로 향하는 하이퍼링크에 문제가 있습니다.

2021-05-24 10:29 UTC, alexkoala requested changes

2021-05-24 10:29 UTC, alexkoala commented on site/content/docs/5.0/utilities/borders.md
> +Border유틸리티는 `scss / _utilities.scss` 의 유틸리티 API에 선언되어 있습니다. [유틸리티 API 사용 방법 알아보기] ({{<docsref "/ utilities / api # using-the-api">}})
```suggestion
Border유틸리티는 `scss/_utilities.scss` 의 유틸리티 API에 선언되어 있습니다. [유틸리티 API 사용 방법 알아보기] ({{<docsref "/utilities/api#using-the-api">}})
```

2021-05-24 10:29 UTC, alexkoala commented on site/content/docs/5.0/utilities/display.md
> +디스플레이 유틸리티는 `scss / _utilities.scss` 의 유틸리티 API에 선언되어 있습니다. [유틸리티 API 사용 방법 알아보기]({{<docsref "/ utilities / api # using-the-api">}})
```suggestion
디스플레이 유틸리티는 `scss/_utilities.scss` 의 유틸리티 API에 선언되어 있습니다. [유틸리티 API 사용 방법 알아보기]({{<docsref "/utilities/api#using-the-api">}})
```

2021-05-24 10:48 UTC, hwang1588 commented on site/content/docs/5.0/utilities/borders.md
> +Border유틸리티는 `scss / _utilities.scss` 의 유틸리티 API에 선언되어 있습니다. [유틸리티 API 사용 방법 알아보기] ({{<docsref "/ utilities / api # using-the-api">}})
확인했습니다! 감사합니다!

2021-05-24 10:48 UTC, hwang1588 commented on site/content/docs/5.0/utilities/display.md
> +디스플레이 유틸리티는 `scss / _utilities.scss` 의 유틸리티 API에 선언되어 있습니다. [유틸리티 API 사용 방법 알아보기]({{<docsref "/ utilities / api # using-the-api">}})
확인했습니다! 감사합니다

2021-05-24 10:49 UTC, hwang1588 commented
하이퍼링크 코드 에러 확인

2021-05-24 10:49 UTC, hwang1588 reviewed
check

2021-05-24 11:31 UTC, jjulee commented
https://github.com/arumduri/bootstrap/pull/25/files#diff-a1b977a6c278d664a6ea1179453b41880f810f8f08c705cd46329ce38959e493L11

https://github.com/arumduri/bootstrap/pull/25/files#diff-a1b977a6c278d664a6ea1179453b41880f810f8f08c705cd46329ce38959e493L40

@hwang1588 
이곳에서 에러나서 수정했습니다만...

2021-05-24 13:44 UTC, alexkoala submitted a review, later dismissed

2021-05-25 00:03 UTC, hwang1588 commented
> https://github.com/arumduri/bootstrap/pull/25/files#diff-a1b977a6c278d664a6ea1179453b41880f810f8f08c705cd46329ce38959e493L11
> 
> https://github.com/arumduri/bootstrap/pull/25/files#diff-a1b977a6c278d664a6ea1179453b41880f810f8f08c705cd46329ce38959e493L40
> 
> @hwang1588
> 이곳에서 에러나서 수정했는데 관련이 있을까요

확인해봤으나 제가 번역 한 문서와 어떤 접점이 있는지 잘 모르겠습니다..😢
@alexkoala 님께서 우선은 #24 현 문서의 병합 여부를 판단해주시면 감사하겠습니다~!

2021-05-25 00:14 UTC, alexkoala commented
@hwang1588 YAML 오류는 제가 병합 후 수정해드릴까요?

2021-05-25 02:00 UTC, hwang1588 commented
> @hwang1588 YAML 오류는 제가 병합 후 수정해드릴까요?

네~! 부탁드립니다!

2021-05-25 03:13 UTC, merged